name: Sickness
version: '${project.version}'
main: xyz.roosterseatyou.sickness.Sickness
api-version: 1.19
authors: [ Roosterseatyou ]
description: Adds disease, sickness, etc. to the game
commands:
  applyfoodpoisoning:
    description: Apply food poisoning
    usage: /applyfoodpoisoning
    permission: sickness.applyfoodpoisoning
    permission-message: You don't have permission to use this command.
  applycold:
    description: Apply cold
    usage: /applycold
    permission: sickness.applycold
    permission-message: You don't have permission to use this command.
  getcoldcure:
    description: Get cold cure
    usage: /getcoldcure
    permission: sickness.getcoldcure
    permission-message: You don't have permission to use this command.